#include<cuda.h> 
#include<cuda_runtime.h> 
#include<bits/stdc++.h> 

using namespace std; 

// FLOATING POINT ADDITION IS NOT ASSOCIATIVE 

/**
 * @brief Block level inclusive scan 
 * 
 * @param input 
 * @param output 
 * @param N 
 * @return __global__ 
 */
__global__ void prefix_sum_blk_kernel(const float* input, float* output, int N) {
    __shared__ float temp[1024]; 
    int tid = threadIdx.x;
    int gid = threadIdx.x + blockDim.x * blockIdx.x; 

    // FIX 1: Check bounds using global ID (gid), not thread ID (tid)
    if (gid < N) {
        temp[tid] = input[gid];
    } else {
        temp[tid] = 0.0f; 
    }
    __syncthreads();

    // Hillis-Steele Scan Algorithm in Shared Memory
    for (int stride = 1; stride < blockDim.x; stride *= 2) {
        float val = temp[tid];
        if (tid >= stride) {
            val += temp[tid - stride];
        }
        __syncthreads(); 
        temp[tid] = val; 
        __syncthreads(); 
    }

    if (gid < N) {
        output[gid] = temp[tid];
    }
}

/**
 * @brief get the sum generated by each block
 * 
 * @param block_sum 
 * @param output 
 * @param Blocks 
 * @param TPB 
 * @param N 
 * @return __global__ 
 */
__global__ void sum_blocks(float* block_sum, const float* output, int Blocks, int TPB, int N) {
    block_sum[0] = 0.0f; 
    for (int i = 1; i < Blocks; i++) {
        // Take the last element of the previous block as that block's total sum
        int prev_last_idx = min(N - 1, i * TPB - 1);
        block_sum[i] = block_sum[i - 1] + output[prev_last_idx]; 
    }
}

// update the global sum 
__global__ void addPrefixSums(float* output, const float* block_sum, int N, int TPB) {
    int tid = threadIdx.x;
    int gid = threadIdx.x + blockDim.x * blockIdx.x; 
    int bid = blockIdx.x;

    if (gid < N && bid > 0) {
        output[gid] += block_sum[bid];
    }
}

extern "C" void solve(const float* input, float* output, int N) {
    int TPB = 1024; 
    int Blocks = (N + TPB - 1) / TPB; 
    
    float* block_sum; 
    cudaMalloc(&block_sum, Blocks * sizeof(float)); 
    // Step 1 Compute independent block-level inclusive scans
    prefix_sum_blk_kernel<<<Blocks, TPB>>>(input, output, N); 
    
    // Step 2 Compute the exclusive prefix sum of block totals (run on 1 thread)
    sum_blocks<<<1, 1>>>(block_sum, output, Blocks, TPB, N); 

    // Step 3 Add the respective block offsets back to each block
    addPrefixSums<<<Blocks, TPB>>>(output, block_sum, N, TPB); 

    cudaDeviceSynchronize();
    cudaFree(block_sum);
}


void assign_rand_val(float* input, int N){
    for( int i = 0 ; i < N ; i++ ){
        input[i] = (float)rand()/(float)RAND_MAX; 
    }
}

void prefix_sum_cpu(float* input, float* output, int N ){
    output[0] = input[0]; 
    for( int i = 1; i < N ; i++ ){
        output[i] = input[i]+ output[i-1]; 
    }
}

int main(){
    int N = 1023; 
    
    // Host varaible pointers declaration and allocation
    float* h_input = (float*)malloc(N*sizeof(float)); 
    float* h_output = (float*)malloc(N*sizeof(float));
    float* goldenTrace = (float*)malloc(N*sizeof(float));

    // generate random values for input array 
    assign_rand_val( h_input, N); 
    
    // Device variables declaration and allocation 
    float* d_input, *d_output; 
    cudaMalloc(&d_input,N*sizeof(float)); 
    cudaMalloc(&d_output,N*sizeof(float)); 

    // copy data from Host to device 
    cudaMemcpy(d_input,h_input,N*sizeof(float),cudaMemcpyHostToDevice); 

    // generate golden trace 
    prefix_sum_cpu(h_input, goldenTrace,N); 

    // lauch kernel to get the GPU output 
    solve(d_input,d_output,N);

    // copy results from device to host 
    cudaMemcpy(h_output,d_output,N*sizeof(float),cudaMemcpyDeviceToHost); 
    
    // compare the results
    int flag = 0; 
    for( int i = 0; i < N; i++ ){
        float diff = fabsf(goldenTrace[i] - h_output[i]);
        float tolerance = 1e-4f + 1e-5f * fabsf(goldenTrace[i]);

        if (diff > tolerance) {
            flag = 1;
            break;
        }
    }

    if( flag ){
        cout << "Device and Host result does not match \n"; 
    }else{
        cout << "Device and Host results matched succesfully \n"; 
    }


    


}